### ISSUE TITLE
"Defined In" paths are incorrect

### ISSUE THREAD

**Issue by rwjblue** [emberjs/api#46]
![image](https://cloud.githubusercontent.com/assets/12637/12439810/ed43a26a-bee9-11e5-91ff-a0f683b40335.png)

**Comment by aaronrenner** [comment]
I haven't seen any issues with the "Defined In" path on the class, but I have seen an issue on "Defined In" for method definitions.

<img width="696" alt="screen shot 2016-01-20 at 12 33 03 am" src="https://cloud.githubusercontent.com/assets/120878/12442505/b927b812-bf0d-11e5-8b56-020283b0aec5.png">

It looks like the issue is in [ember-cli-yuidoc-converter](https://github.com/trek/ember-cli-yuidoc-converter/blob/master/addon/index.js). The `projectFilePath` method is [being called](https://github.com/trek/ember-cli-yuidoc-converter/blob/master/addon/index.js#L204-L207) when generating the json for the class definition, but not when generating the json for the method definition file.

**Comment by rwjblue** [comment]
I think in general the defined in should match what we have today in emberjs.com/api. Meaning we need to figure out how to ensure it is an http URL pointing at the source on github.

I totally agree that this might be an issue in ember-cli-YUIDoc-converter, we can open an issue over there but I'd also like to keep this open for general tracking purposes.

**Comment by rwjblue** [comment]
I believe that https://github.com/emberjs/api/pull/64 fixes this.  I think I was using the wrong arguments :(

**Comment by locks** [comment]
https://github.com/emberjs/website/issues/2455 kinda related. How does this app deal with those?

**Comment by rwjblue** [comment]
@locks - I'm not sure just yet, need to dig in more.

**Comment by rwjblue** [comment]
I believe this is actually fine, and that I had misconfigured the options passed in.  Closing for now...
